### ISSUE TITLE
What are the functions of "ADcmd" and "FTcmd" in "pipe.sh"?

### ISSUE THREAD

**Issue by tiesanguaixia** [yangbang18/MultiCapCLIP#3]
Thank you for the great work and code sharing. I find that `ADcmd` and `FTcmd` in `pipe.sh` are not explicitly designated and initialized with two empty strings, but they are still part of the commands like:
```bash
python3 adapt.py --pickle --dataset ${dataset} --method ${method} $ADcmd
```
So what are the functions of these two variables? Thank you in advance!

**Comment by yangbang18** [comment]
Just for the cases in which you have not formally defined a method in configs/methods.yaml, but want to modify some arguments of a specific method. It's ok to delete `Adcmd` and `FTcmd`.

**Comment by tiesanguaixia** [comment]
> Just for the cases in which you have not formally defined a method in configs/methods.yaml, but want to modify some arguments of a specific method. It's ok to delete `Adcmd` and `FTcmd`.

Thanks a lot!
