### ISSUE TITLE
How to obtain relevant concept prompts during the inference of MultiCapCLIP on video captioning task?

### ISSUE THREAD

**Issue by tiesanguaixia** [yangbang18/MultiCapCLIP#5]
Thank you for the great work and code sharing! During the inference of `MultiCapCLIP` on video captioning task, do you average all embeddings of frames extracted from the video to get **one** video embedding and use the video embedding to obtain related concept prompts or there are some other detailed operations? 
Thank you in advance!

**Comment by yangbang18** [comment]
Q1: During the inference of MultiCapCLIP on video captioning task, do you average all embeddings of frames extracted from the video to get one video embedding?
A1: Assuming that there are `T` sampled frames from a video (`T=8` in our [code](https://github.com/yangbang18/MultiCapCLIP/blob/d80b537019585a3e241235097c55875b9512b0dc/configs/__init__.py#L20)), we do not average their embeddings and feed all `T` frames into the model. You can refer to this [line](https://github.com/yangbang18/MultiCapCLIP/blob/d80b537019585a3e241235097c55875b9512b0dc/models/clip_projecter.py#L30), where we do not specify the argument `average_pooling`, so it default to `False`

Q2: How to get relevant concept prompts when the input is a video
A2: You can refer to this [line](https://github.com/yangbang18/MultiCapCLIP/blob/d80b537019585a3e241235097c55875b9512b0dc/models/clip_projecter.py#L73), where we calculate the cosine similarity between `T` frames and `N` concept prompts, then obtain a matrix of shape `(Batch_size, T, N)`, then get similarity of each sample by averaging the matrix over `T`.

**Comment by tiesanguaixia** [comment]
> Q1: During the inference of MultiCapCLIP on video captioning task, do you average all embeddings of frames extracted from the video to get one video embedding? A1: Assuming that there are `T` sampled frames from a video (`T=8` in our [code](https://github.com/yangbang18/MultiCapCLIP/blob/d80b537019585a3e241235097c55875b9512b0dc/configs/__init__.py#L20)), we do not average their embeddings and feed all `T` frames into the model. You can refer to this [line](https://github.com/yangbang18/MultiCapCLIP/blob/d80b537019585a3e241235097c55875b9512b0dc/models/clip_projecter.py#L30), where we do not specify the argument `average_pooling`, so it default to `False`
> 
> Q2: How to get relevant concept prompts when the input is a video A2: You can refer to this [line](https://github.com/yangbang18/MultiCapCLIP/blob/d80b537019585a3e241235097c55875b9512b0dc/models/clip_projecter.py#L73), where we calculate the cosine similarity between `T` frames and `N` concept prompts, then obtain a matrix of shape `(Batch_size, T, N)`, then get similarity of each sample by averaging the matrix over `T`.

Thanks a lot for your detailed reply! So the shape of `encoder_hidden_states` in this [line](https://github.com/yangbang18/MultiCapCLIP/blob/d80b537019585a3e241235097c55875b9512b0dc/models/AdaCLIP.py#L397C19-L397C19) during inference for image captioning and video captioning is `(batch_size, 1, dim)` and `(batch_size, num_frame, dim)` respectively, both of the shape have 3 dimensions. Is this correct?

**Comment by yangbang18** [comment]
> > Q1: During the inference of MultiCapCLIP on video captioning task, do you average all embeddings of frames extracted from the video to get one video embedding? A1: Assuming that there are `T` sampled frames from a video (`T=8` in our [code](https://github.com/yangbang18/MultiCapCLIP/blob/d80b537019585a3e241235097c55875b9512b0dc/configs/__init__.py#L20)), we do not average their embeddings and feed all `T` frames into the model. You can refer to this [line](https://github.com/yangbang18/MultiCapCLIP/blob/d80b537019585a3e241235097c55875b9512b0dc/models/clip_projecter.py#L30), where we do not specify the argument `average_pooling`, so it default to `False`
> > Q2: How to get relevant concept prompts when the input is a video A2: You can refer to this [line](https://github.com/yangbang18/MultiCapCLIP/blob/d80b537019585a3e241235097c55875b9512b0dc/models/clip_projecter.py#L73), where we calculate the cosine similarity between `T` frames and `N` concept prompts, then obtain a matrix of shape `(Batch_size, T, N)`, then get similarity of each sample by averaging the matrix over `T`.
> 
> Thanks a lot for your detailed reply! So the shape of `encoder_hidden_states` in this [line](https://github.com/yangbang18/MultiCapCLIP/blob/d80b537019585a3e241235097c55875b9512b0dc/models/AdaCLIP.py#L397C19-L397C19) during inference for image captioning and video captioning is `(batch_size, 1, dim)` and `(batch_size, num_frame, dim)` respectively, both of the shape have 3 dimensions. Is this correct?

Yes, you are right.

**Comment by tiesanguaixia** [comment]
> > > Q1: During the inference of MultiCapCLIP on video captioning task, do you average all embeddings of frames extracted from the video to get one video embedding? A1: Assuming that there are `T` sampled frames from a video (`T=8` in our [code](https://github.com/yangbang18/MultiCapCLIP/blob/d80b537019585a3e241235097c55875b9512b0dc/configs/__init__.py#L20)), we do not average their embeddings and feed all `T` frames into the model. You can refer to this [line](https://github.com/yangbang18/MultiCapCLIP/blob/d80b537019585a3e241235097c55875b9512b0dc/models/clip_projecter.py#L30), where we do not specify the argument `average_pooling`, so it default to `False`
> > > Q2: How to get relevant concept prompts when the input is a video A2: You can refer to this [line](https://github.com/yangbang18/MultiCapCLIP/blob/d80b537019585a3e241235097c55875b9512b0dc/models/clip_projecter.py#L73), where we calculate the cosine similarity between `T` frames and `N` concept prompts, then obtain a matrix of shape `(Batch_size, T, N)`, then get similarity of each sample by averaging the matrix over `T`.
> > 
> > 
> > Thanks a lot for your detailed reply! So the shape of `encoder_hidden_states` in this [line](https://github.com/yangbang18/MultiCapCLIP/blob/d80b537019585a3e241235097c55875b9512b0dc/models/AdaCLIP.py#L397C19-L397C19) during inference for image captioning and video captioning is `(batch_size, 1, dim)` and `(batch_size, num_frame, dim)` respectively, both of the shape have 3 dimensions. Is this correct?
> 
> Yes, you are right.

Thanks a lot!
